# Generated by Django 5.2.3 on 2025-07-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='skillproof',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proofs', to='users.profile'),
        ),
    ]
