# Generated by Django 5.2.3 on 2025-07-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_id'),
        ('users', '0004_remove_profile_cv_text_profile_cv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
    ]
