# Generated by Django 5.2.3 on 2025-07-11 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobapplication_unique_together'),
        ('users', '0004_remove_profile_cv_text_profile_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreview',
            name='value',
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jobs.jobapplication'),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='reviewer',
            field=models.ForeignKey(default=3, limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
